### PR TITLE
Add 2025 prospectus

### PR DESCRIPTION
**Pull request by nimbinatus**
Adding the prospectus and cleaning up some links the build is complaining about. Also hid any poetry build tooling while I was here.

### CODE REVIEW

**Comment by nimbinatus** [comment]
Screenshot from 2024-07-12 17-42-09
Screenshot from 2024-07-12 17-42-12
Screenshot from 2024-07-12 17-42-16
Screenshot from 2024-07-12 17-42-20

**Review by dijital20 — APPROVED** [review]
Looks good to me.

**Review by toonarmycaptain — APPROVED** [review]
I kinda like $10k rather than $9k because round numbers, but everything looks great to me.

**Review by MasonEgger — APPROVED** [review]
LGTM. Ship it

**Pull request merged**
